server:
  port: 8120 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-sms # 服务名

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  # nacos服务地址

  #spring:
  redis:
    host: 82.157.192.119
    port: 6379
    database: 0
    password: krian18723220402 #默认为空
    timeout: 3000ms #最大等待时间，超时则抛出异常，否则请求一直等待
    lettuce:
      pool:
        max-active: 20  #最大连接数，负值表示没有限制，默认8
        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
        max-idle: 8     #最大空闲连接，默认8
        min-idle: 0     #最小空闲连接，默认0

#阿里云短信
aliyun:
  sms:
    region-id: cn-hangzhou
    key-id: LTAI4G5Svnb2TWBMuKnNT6jY
    key-secret: N7v6R4V3EJ1SGDZlsqtqo8QyVVMmtQ
    template-code: SMS_96695065
    sign-name: krian

# openfeign 请求超时设置：
feign:
  client:
    config:
      default:
        connectTimeout: 10000  #连接超时时间
        read-timeout: 600000   #执行超时时间

  # 开启服务熔断支持：
  sentinel:
    enabled: true

# 设置日志级别：
logging:
  level:
    com.krian.finance.sms.client.CoreUserInfoClient: DEBUG  #以指定级别监控指定接口